services:
  postgres:
    image: postgres:16
    container_name: splitnest_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: splitnest_user
      POSTGRES_PASSWORD: splitnest_pass
      POSTGRES_DB: splitnest
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
